version: '3'

services:
    python-api:
        image: yournightmare777/server-ab
        container_name: "server-ab"
        restart: on-failure
        ports:
            - "0.0.0.0:5000:5000"
        volumes:
            - /proc/cpu-info:/usr/src/app/cpu.txt
            - /proc/ram-info:/usr/src/app/ram.txt
        depends_on:
            - mongodb

    mongodb:
        image: mongo
        container_name: "mongo-container"
        ports:
            - "0.0.0.0:27017:27017"
