version: '3'

services:
    python-api:
        build: .
        command: python -u app.py
        ports:
            - "0.0.0.0:5000:5000"
        volumes:
            - /proc/cpu-info:/app/src/cpu.txt
            - /proc/ram-info:/app/src/ram.txt
        depends_on:
            -mongodb
            
    mongodb:
        image: mongo
        container_name: "mongo-container"
        ports:
            - "0.0.0.0:27017:27017"